PruebaTecnicaCorporacionTAK/Models/COLABORADOR.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnicaCorporacionTAK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLABORADOR
    {
        public int IdColaborador { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string EstadoCivil { get; set; }
        public string GradoAcademico { get; set; }
        public string Direccion { get; set; }
    }
}

PruebaTecnicaCorporacionTAK/Models/Request/Colaborador.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PruebaTecnicaCorporacionTAK.Models.Request
{
    public class Colaborador
    {
        public int IdColaborador { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string  FechaNacimiento { get; set; }
        public string EstadoCivil { get; set; }
        public string GradoAcademico { get; set; }
        public string Direccion { get; set; }
    }
}

PruebaTecnicaCorporacionTAK/Models/ViewModel/ColaboradorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace PruebaTecnicaCorporacionTAK.Models.ViewModel
{
    public class ColaboradorViewModel
    {
        public int IdColaborador { get; set; }

        [Required]
        [Display(Name ="Nombres")]
        public string Nombres { get; set; }

        [Required]
        [Display(Name = "Apellidos")]
        public string Apellidos { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha de Nacimiento")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime FechaNacimiento { get; set; }

        [Required]
        [Display(Name = "Estado Civil")]
        public string EstadoCivil { get; set; }

        [Required]
        [Display(Name = "Grado Académico")]
        public string GradoAcademico { get; set; }

        [Required]
        [Display(Name = "Dirección")]
        public string Direccion { get; set; }
    }
}

PruebaTecnicaCorporacionTAK/Controllers/ColaboradorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PruebaTecnicaCorporacionTAK.Models;
using PruebaTecnicaCorporacionTAK.Models.ViewModel;
using PruebaTecnicaCorporacionTAK.Models.Request;
using System.IdentityModel.Tokens.Jwt;
using System.Text;
using Microsoft.IdentityModel.Tokens;
using System.Security.Claims;
using PruebaTecnicaCorporacionTAK.Models.Common;

namespace PruebaTecnicaCorporacionTAK.Controllers
{
    public class ColaboradorController : Controller
    {
        // GET: Colaborador
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(ColaboradorViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            try
            {
                using (var db = new PruebaTecnicaTakDBEntities())
                {
                    db.SP_INSERTAR_COLABORADOR(model.Nombres, model.Apellidos, model.FechaNacimiento, model.EstadoCivil, model.GradoAcademico, model.Direccion);
                    db.SaveChanges();
                    return Redirect(Url.Content("Index"));
                }

            }
            catch (Exception ex)
            {

                return View(ex.Message);
            }
        }

        [HttpGet]
        public JsonResult getAllColaborador()
        {
            try
            {
                List<Colaborador> listColaborador = new List<Colaborador>();
                using (var db = new PruebaTecnicaTakDBEntities())
                {
                    foreach(var oElement in db.SP_LISTA_COLABORADOR())
                    {
                        var oColaborador = new Colaborador()
                        {
                            IdColaborador = oElement.IdColaborador,
                            Nombres = oElement.Nombres,
                            Apellidos = oElement.Apellidos,
                            FechaNacimiento = (String.Format("{0:dd/MM/yyyy}", oElement.FechaNacimiento)),
                            EstadoCivil = oElement.EstadoCivil,
                            GradoAcademico = oElement.GradoAcademico,
                            Direccion = oElement.Direccion
                        };
                        listColaborador.Add(oColaborador);
                    }
                }
                return Json(listColaborador, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            using (var db = new PruebaTecnicaTakDBEntities())
            {
                db.SP_ELIMINAR_COLABORADOR(id);
                db.SaveChanges();
            }


            return Content("1");
        }
        [HttpGet]
        public ActionResult Update(int Id)
        {
            var model = new ColaboradorViewModel();
            using (var db = new PruebaTecnicaTakDBEntities())
            {
                var oColaborador = db.COLABORADOR.Find(Id);
                model.IdColaborador = oColaborador.IdColaborador;
                model.Nombres = oColaborador.Nombres;
                model.Apellidos = oColaborador.Apellidos;
                model.FechaNacimiento = oColaborador.FechaNacimiento;
                model.EstadoCivil = oColaborador.EstadoCivil;
                model.GradoAcademico = oColaborador.GradoAcademico;
                model.Direccion = oColaborador.Direccion;
   
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult Update(ColaboradorViewModel model)
        {
            using (var db = new PruebaTecnicaTakDBEntities())
            {
                db.SP_ACTUALIZAR_COLABORADOR(model.IdColaborador,model.Nombres, model.Apellidos, model.FechaNacimiento, model.EstadoCivil, model.GradoAcademico, model.Direccion);
                db.SaveChanges();
            }


            return Redirect(Url.Content("~/Colaborador"));
        }
        
        [HttpPost]
        public JsonResult generateWebToken(int Id)
        {

            try
            {
                List<String> jwt = new List<string>();
                jwt.Add(GetToken(Id));

                return Json(jwt, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }


        static string GetToken(int Id)
        {
            var model = new ColaboradorViewModel();
            using (var db = new PruebaTecnicaTakDBEntities())
            {
                var oColaborador = db.COLABORADOR.Find(Id);
                model.IdColaborador = oColaborador.IdColaborador;
                model.Nombres = oColaborador.Nombres;
                model.Apellidos = oColaborador.Apellidos;
                model.FechaNacimiento = oColaborador.FechaNacimiento;
                model.EstadoCivil = oColaborador.EstadoCivil;
                model.GradoAcademico = oColaborador.GradoAcademico;
                model.Direccion = oColaborador.Direccion;

            }

            var tokenHandler = new JwtSecurityTokenHandler();
            var llave = Encoding.ASCII.GetBytes("12381989as19383239s393923293993s93ad9393");
            var tokenDescriptor = new SecurityTokenDescriptor
            {
                Subject = new ClaimsIdentity(
                    new Claim[]
                    {
                        new Claim(ClaimTypes.NameIdentifier, model.IdColaborador.ToString()),
                        new Claim(ClaimTypes.Name, model.Nombres),
                        new Claim(ClaimTypes.Name, model.Apellidos)
                    }
                    ),
                Expires = DateTime.UtcNow.AddSeconds(60),
                SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(llave), SecurityAlgorithms.HmacSha256Signature)
            };
            var token = tokenHandler.CreateToken(tokenDescriptor);

            return tokenHandler.WriteToken(token);
        }
    }
}

PruebaTecnicaCorporacionTAK/Views/Colaborador/Add.cshtml
@model PruebaTecnicaCorporacionTAK.Models.ViewModel.ColaboradorViewModel
@{
    ViewBag.Title = "Registrar nuevo colaborador";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Add", "Colaborador", FormMethod.Post, new { role = "form" }))
{
    <div class="row g-2">
        <div class="col-md-6   ">
            @Html.LabelFor(d => d.Nombres, new { @class = "form-label" })

            @Html.TextBoxFor(d => d.Nombres, new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.Nombres, "", new { @class = "text-danger" })<br />
        </div>
        <div class="col-md-4 row">
            @Html.LabelFor(d => d.Apellidos, new { @class = "form-label" })

            @Html.TextBoxFor(d => d.Apellidos, new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.Apellidos, "", new { @class = "text-danger" })<br />
        </div>


        <div class="col-md-6 ">
            @Html.LabelFor(d => d.FechaNacimiento, new { @class = "form-label" })<br />

            @Html.EditorFor(d => d.FechaNacimiento, new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.FechaNacimiento, "", new { @class = "text-danger" })<br />
        </div>
        <div class="col-md-4 row">
            <label for="inputState" class="form-label">Estado Civil</label>
            @Html.TextBoxFor(d => d.EstadoCivil, new { @class = "form-control", hidden = true, id = "idEstadoCiv" })
            <select id="inputEstadoCivil" class="form-select">
                <option selected>Soltero</option>
                <option>Casado</option>
                <option>Viudo</option>
            </select>
            @Html.ValidationMessageFor(d => d.EstadoCivil, "", new { @class = "text-danger" })<br />
        </div>

        <div class="col-10 row mt-5">
            @Html.LabelFor(d => d.GradoAcademico, new { @class = "form-label" })<br />

            @Html.TextBoxFor(d => d.GradoAcademico, new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.GradoAcademico, "", new { @class = "text-danger" })<br />
        </div>
        
        <div class="col-10 row">
            @Html.LabelFor(d => d.Direccion, new { @class = "form-label" })<br />

            @Html.TextAreaFor(d => d.Direccion, new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.Direccion, "", new { @class = "text-danger" })<br />
        </div>
        
        <div class="col-12">
            <a class="btn btn-outline-dark" href="@Url.Content("~/Colaborador/Index")">Cancelar</a>
            <button type="submit" class="btn btn-primary">Guardar</button>

        </div>
    </div>
}

<script>

    document.getElementById("idEstadoCiv").value = "Soltero";
    var select = document.getElementById('inputEstadoCivil');
    select.addEventListener('change',
        function () {
            var selectedOption = this.options[select.selectedIndex];
            document.getElementById("idEstadoCiv").value = selectedOption.text;
        });
   
</script>

PruebaTecnicaCorporacionTAK/Views/Colaborador/Index.cshtml
@{
    ViewBag.Title = "COLABORADORES";
}

<h2>@ViewBag.Title</h2>

<div class="col-12">
    
    <a href="@Url.Content("~/Colaborador/Add")" class="btn btn-success">
        +  Nuevo
    </a>
</div>
<hr />

<div class="row">
    <div class="col-md-12">
        <table class="table" id="tColaborador">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nombre</th>
                    <th>Fecha Nacimiento</th>
                    <th>Estado Civil</th>
                    <th>Grado Académico</th>
                    <th>Dirección</th>
                </tr>
            </thead>
            <tbody id="tbodyColab">

            </tbody>
        </table>

    </div>
</div>

<script>
    getAllColaborador();
    function getAllColaborador() {
        var url = "@Url.Content("~/Colaborador/getAllColaborador")";
        fetch(url).then(function (response) {
            return response.json();
        }).then(function (Data) {
            document.getElementById("tColaborador").innerHTML = "";
            for (i = 0; i < Data.length; i++) {
                let Tabla = document.getElementById("tColaborador");
                var TR = document.createElement("tr");

                let tabButtonDelete = document.createElement("button");
                let tabButtonEdit = document.createElement("button");
                let tabButtonToken = document.createElement("button");


                tabButtonDelete.innerHTML = "Eliminar";
                tabButtonEdit.innerHTML = "Editar";
                tabButtonToken.innerHTML = "Token";

                tabButtonDelete.classList.add('btn');
                tabButtonDelete.classList.add('btn-danger');
                tabButtonDelete.classList.add('m-1');

                tabButtonEdit.classList.add('btn');
                tabButtonEdit.classList.add('btn-outline-primary');
                tabButtonEdit.classList.add('m-1');

                tabButtonToken.classList.add('btn');
                tabButtonToken.classList.add('btn-outline-success');
                tabButtonToken.classList.add('m-1');

                tabButtonEdit.cIdColab = Data[i].IdColaborador;
                tabButtonEdit.addEventListener("click", function (mibutton) {
                    mibutton.preventDefault();

                    jsEditar(mibutton.target.cIdColab);
                });

                tabButtonDelete.cIdColab = Data[i].IdColaborador;
                tabButtonDelete.addEventListener("click", function (mibutton) {
                    mibutton.preventDefault();
                    jsEliminar(mibutton.target.cIdColab);
                });

                tabButtonToken.cIdColab = Data[i].IdColaborador;
                tabButtonToken.addEventListener("click", function (mibutton) {
                    mibutton.preventDefault();
                    jswt(mibutton.target.cIdColab);
                });

                let TdId = document.createElement("td");
                let TdNombre = document.createElement("td");
                let TdFechaNac = document.createElement("td");
                let TdEstadoCiv = document.createElement("td");
                let TdGradoAc = document.createElement("td");
                let TdDireccion = document.createElement("td");


                let TDBtnEdit = document.createElement("td");
                let TDBtnDelet = document.createElement("td");
                TDBtnEdit = tabButtonEdit;
                TDBtnDelet = tabButtonDelete;
                TDBtnToken = tabButtonToken;

                TR.appendChild(TdId);
                TR.appendChild(TdNombre);
                TR.appendChild(TdFechaNac);
                TR.appendChild(TdEstadoCiv);
                TR.appendChild(TdGradoAc);
                TR.appendChild(TdDireccion);
                TR.appendChild(TDBtnDelet);
                TR.appendChild(TDBtnEdit);
                TR.appendChild(TDBtnToken);



                TdId.innerHTML = Data[i].IdColaborador;
                TdNombre.innerHTML = Data[i].Nombres + " " + Data[i].Apellidos;
                TdFechaNac.innerHTML = Data[i].FechaNacimiento;
                TdEstadoCiv.innerHTML = Data[i].EstadoCivil;
                TdGradoAc.innerHTML = Data[i].GradoAcademico;
                TdDireccion.innerHTML = Data[i].Direccion;

                Tabla.appendChild(TR);
            }
        })
    }

    function jsEliminar(Id)
    {
        urld = "@Url.Content("~/Colaborador/Delete")" + "/" + Id;
        $.post(urld, function (data) {
            if (data == "1")
            {
                document.location.href = "@Url.Content("~/Colaborador/Index")";
            }
            else
            {
                alert("Ocurrió un error!!");
            }

        })
    }



    function jsEditar(Id) {
        document.location.href = "@Url.Content("~/Colaborador/Update")" + "/" + Id;
    }

    function jswt(Id)
    {

        urld = "@Url.Content("~/Colaborador/generateWebToken")" + "/" + Id;
        $.post(urld, function (data) {
            console.log(data)
        })
    }
</script>

PruebaTecnicaCorporacionTAK/Views/Colaborador/TokenRequest.cshtml
@{
    ViewBag.Title = "TokenRequest";
}

<h2>TokenRequest</h2>
<div class="row">
    <div class="col-lg-4">
        <p class="text-center">
            @Request["token"]

        </p>
    </div>
</div>

PruebaTecnicaCorporacionTAK/Views/Colaborador/Update.cshtml
@model PruebaTecnicaCorporacionTAK.Models.ViewModel.ColaboradorViewModel
@{
    ViewBag.Title = "Actualizar datos";
}

<h2>@ViewBag.Title</h2>



@using (Html.BeginForm("Update", "Colaborador", FormMethod.Post, new { role = "form" }))
{
    <div class="row g-2">
          @Html.TextBoxFor(d => d.IdColaborador, new { @class = "form-control",hidden = true })

        <div class="col-md-6   ">
            @Html.LabelFor(d => d.Nombres, new { @class = "form-label" })

            @Html.TextBoxFor(d => d.Nombres, new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.Nombres, "", new { @class = "text-danger" })<br />
        </div>
        <div class="col-md-4 row">
            @Html.LabelFor(d => d.Apellidos, new { @class = "form-label" })

            @Html.TextBoxFor(d => d.Apellidos, new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.Apellidos, "", new { @class = "text-danger" })<br />
        </div>


        <div class="col-md-6 ">
            @Html.LabelFor(d => d.FechaNacimiento, new { @class = "form-label" })<br />

            @Html.EditorFor(d => d.FechaNacimiento, new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.FechaNacimiento, "", new { @class = "text-danger" })<br />
        </div>
        <div class="col-md-4 row">
            <label for="inputState" class="form-label">Estado Civil</label>
            @Html.TextBoxFor(d => d.EstadoCivil, new { @class = "form-control", hidden = true, id = "idEstadoCiv" })
            <select id="inputEstadoCivil" class="form-select">
                <option selected>Soltero</option>
                <option>Casado</option>
                <option>Viudo</option>
            </select>
            @Html.ValidationMessageFor(d => d.EstadoCivil, "", new { @class = "text-danger" })<br />
        </div>

        <div class="col-10 row mt-5">
            @Html.LabelFor(d => d.GradoAcademico, new { @class = "form-label" })<br />

            @Html.TextBoxFor(d => d.GradoAcademico, new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.GradoAcademico, "", new { @class = "text-danger" })<br />
        </div>

        <div class="col-10 row">
            @Html.LabelFor(d => d.Direccion, new { @class = "form-label" })<br />

            @Html.TextAreaFor(d => d.Direccion, new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.Direccion, "", new { @class = "text-danger" })<br />
        </div>

        <div class="col-12">
            <a class="btn btn-outline-dark" href="@Url.Content("~/Colaborador/Index")">Cancelar</a>
            <button type="submit" class="btn btn-primary">Guardar</button>

        </div>
    </div>
}

<script>

    //document.getElementById("idEstadoCiv").value = "Soltero";
    var select = document.getElementById('inputEstadoCivil');
    select.addEventListener('change',
        function () {
            var selectedOption = this.options[select.selectedIndex];
            document.getElementById("idEstadoCiv").value = selectedOption.text;
        });
 
</script>